import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-12">
          <header>
            <Link href="/" className="text-2xl font-bold">
              Home
            </Link>
          </header>
          <main className="mt-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
